--- #YAML:1.0
name:               Linux-IO_Prio
version:            0.02
abstract:           Interface to Linux ioprio_set and ioprio_get via syscall or ionice wrapper.
author:
    - Mark Hindley <mark@hindley.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
